name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        #pylint `ls -R|grep .py$|xargs` see: https://stackoverflow.com/questions/68860511/github-actions-pylint-fails-with-f0001-no-module-named-init-py-fatal
        python -m pylint --fail-under=8 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pylint report
        path: pylint.txt
