name: Build and publish to test.pypi

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build package
      run: |
        pip install build
        python -m build
    - name: Publish a Python distribution to PyPI test
      run: |
        pip install twine
        twine upload --username ${{ user }} --password ${{ password }} --non-interactive --repository ${{ repo }} dist/* --verbose
      env:
        user: __token__
        password: ${{ secrets.TESTPYPI_PSW }}
        #repository_url: https://test.pypi.org/legacy/
        verbose: true
        repo: testpypi
