name: Publish Python distributions to PyPI

on: [push]

jobs:
    build-n-publish:
      name: Publish a Python distribution to PyPI
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_PSW }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
